// Hand-authored pixel icons for level-up cards and Armory perks. Letters are
// colour ramps from pixelart.js (lowercase = auto-shaded, uppercase = forced
// highlight, '*' glint, '#' ink); pixelSprite() adds the outline.

const ICON_MAPS = {
  // ---- Stat upgrades ----
  fireRate: [ // lightning bolt
    ".........yyy",
    "........yyy.",
    ".......yyy..",
    "......yyy...",
    ".....yyy....",
    "....yyyyyyy.",
    "...yyyyyyy..",
    "......yyy...",
    ".....yyy....",
    "....yyy.....",
    "...yy.......",
    "..yy........",
    ".y..........",
  ],
  damage: [ // a sharpened round
    "...w...",
    "..wWw..",
    "..wWw..",
    ".wwWww.",
    ".wwwww.",
    "wwwwwww",
    "ggggggg",
    "gGggggg",
    "gGggggg",
    "gGggggg",
    "gGggggg",
    "gGggggg",
    "ggggggg",
    "mmmmmmm",
  ],
  speed: [ // winged boot
    "......mmmmm.....",
    "w.....mMmmm.....",
    "ww....mMmmm.....",
    "www...mmmmm.....",
    ".wwww.mmmmm.....",
    "..wwwwmmmmm.....",
    "....wwmmmmm.....",
    "......mmmmmm....",
    "......mmmmmmmm..",
    "......mmmmmmmmm.",
    "......kkkkkkkkk.",
  ],
  maxHp: [ // heart
    ".rrr...rrr.",
    "rRRrr.rrrrr",
    "rRrrrrrrrrr",
    "rrrrrrrrrrr",
    "rrrrrrrrrrr",
    ".rrrrrrrrr.",
    "..rrrrrrr..",
    "...rrrrr...",
    "....rrr....",
    ".....r.....",
  ],
  bulletSpeed: [ // comet
    "............ww..",
    "..........wwWWw.",
    "........ccwWWWw.",
    "......cccwwWWww.",
    "....ccccwwwwww..",
    "..cccccwwwww....",
    "ccccccccccc.....",
    "..ccccc.........",
    "cccc............",
  ],
  staminaRegen: [ // feather
    "..........bb",
    "........bbbb",
    ".......bbbbB",
    "......bbbbB.",
    ".....bbbbB..",
    "....bbbbB...",
    "...bbbbb....",
    "...bbbb.....",
    "..bbb.......",
    "..b.........",
    ".w..........",
    "w...........",
  ],
  maxStamina: [ // shield with a star
    "gggggggggg",
    "gbbbbbbbbg",
    "gbBbbbbbbg",
    "gbBbbybbbg",
    "gbbbyyybbg",
    "gbbbbybbbg",
    ".gbbbbbbg.",
    ".gbbbbbbg.",
    "..gbbbbg..",
    "...gbbg...",
    "....gg....",
  ],
  magnet: [
    "..rrrrrrrr..",
    ".rRRrrrrrrr.",
    "rrRr....rrrr",
    "rrr......rrr",
    "rrr......rrr",
    "rrr......rrr",
    "rrr......rrr",
    "www......www",
    "WWw......WWw",
    "www......www",
  ],
  backpack: [ // satchel with a gold buckle
    "....kkkk....",
    "...k....k...",
    ".mmmmmmmmmm.",
    "mmMMMMMMMMmm",
    "mmmmmmmmmmmm",
    "mmmmmgggmmmm",
    "mmmmmgygmmmm",
    "mmmmmgggmmmm",
    "mmmmmmmmmmmm",
    "mmmmmmmmmmmm",
    ".mmmmmmmmmm.",
  ],
  regen: [ // green cross with sparkles
    "*.........*",
    "....nnn....",
    "....nNn....",
    "....nnn....",
    ".nnnnnnnnn.",
    ".nNNNnnnnn.",
    ".nnnnnnnnn.",
    "....nnn....",
    "....nnn....",
    "....nnn....",
    "*.........*",
  ],
  multishot: [ // three bolts fanning out of one
    "bb.....bb.....bb",
    "bBb....bB....bBb",
    ".bBb...bB...bBb.",
    "..bBb..bB..bBb..",
    "...bb..bb..bb...",
    "....b..bb..b....",
    ".....b.bb.b.....",
    "......bbbb......",
    "......bwwb......",
    ".....bwWWwb.....",
    ".....bwWWwb.....",
    "......bwwb......",
    ".......bb.......",
  ],
  pierce: [ // arrow through a target
    ".....rrrrrr.....",
    "...rrwwwwwwrr...",
    "..rwwrrrrrrwwr..",
    ".rwrrwwwwwwrrwr.",
    ".rwrwwrrrrwwrwrw",
    "rwrwrrwwwwrrwrww",
    "mmmmmmmmmmmmmmww",
    "rwrwrrwwwwrrwrww",
    ".rwrwwrrrrwwrwrw",
    ".rwrrwwwwwwrrwr.",
    "..rwwrrrrrrwwr..",
    "...rrwwwwwwrr...",
    ".....rrrrrr.....",
  ],
  bigDamage: [ // overcharged orb
    "...pppp...",
    ".pppppppp.",
    ".ppPPpypp.",
    "ppPppyyppp",
    "pppppyyppp",
    "ppppyyyypp",
    "pppppyyppp",
    ".ppppyppp.",
    ".pppppppp.",
    "...pppp...",
  ],
  glassCannonSpeed: [ // rocket on an afterburner
    "......ww......",
    ".....wwww.....",
    "....wwWwww....",
    "....wWwwww....",
    "....wWwbww....",
    "....wwbbww....",
    "...rwwwwwwr...",
    "..rrwwwwwwrr..",
    "..rr.wwww.rr..",
    "......oo......",
    ".....oyyo.....",
    "......oo......",
    "......o.......",
  ],
  tripleShot: [ // three stars
    "...y......y...",
    "..yyy....yyy..",
    "yyyyyy..yyyyyy",
    "..yyy....yyy..",
    "..y.y....y.y..",
    "......y.......",
    ".....yyy......",
    "...yyyyyyy....",
    ".....yyy......",
    ".....y.y......",
  ],

  // ---- Wild cards ----
  blankRoll: [ // circle with a slash
    "....cccc....",
    "..cc....cc..",
    ".c.......wc.",
    ".c......w.c.",
    "c......w...c",
    "c.....w....c",
    "c....w.....c",
    "c...w......c",
    ".c.w......c.",
    ".cw.......c.",
    "..cc....cc..",
    "....cccc....",
  ],
  bulletTime: [ // hourglass
    "gggggggggg",
    ".wwwwwwww.",
    ".wyyyyyyw.",
    "..wyyyyw..",
    "...wyyw...",
    "....ww....",
    "...wwyw...",
    "..wwwyww..",
    ".wwwyyyww.",
    ".wyyyyyyw.",
    "gggggggggg",
  ],
  moon: [ // crescent moon and stars
    ".....wwwww......",
    "...wwwwww.......",
    "..wwwww.......*.",
    ".wwwww.......***",
    ".wwww.........*.",
    "wwwww...........",
    "wwwww......*....",
    "wwwww...........",
    ".wwwww..........",
    ".wwwwww.........",
    "..wwwwwwww......",
    "...wwwwwwwwww...",
    ".....wwwwwwww...",
  ],
  rubber: [ // bouncing ball
    "........rrrr....",
    ".......rRRrrr...",
    "......rRRrrrrr..",
    "......rRrrrrrr..",
    "......rrrrrrrr..",
    ".......rrrrrr...",
    "........rrrr....",
    "................",
    "..w.............",
    ".w.w............",
    "w...w......w....",
    ".....w....w.....",
    "......w..w......",
    ".......ww.......",
  ],
  corpse: [ // burning skull
    ".....o.....",
    "....oyo....",
    "...wwwww...",
    "..wwwwwww..",
    ".wwwwwwwww.",
    ".ww##w##ww.",
    ".ww##w##ww.",
    ".wwwwwwwww.",
    "..www#www..",
    "...wwwww...",
    "...w.w.w...",
  ],
  dice: [ // a pair of dice
    "..wwwwwwww......",
    ".wWWWWWWWww.....",
    ".wW##ww##ww.....",
    ".wW##ww##ww.....",
    ".wwwwwwwwww.....",
    ".wwwwwwwwww.....",
    ".wW##ww##ww.....",
    ".wW##ww##wrrrrr.",
    ".wwwwwwwwrRRRRrr",
    "..wwwwwwwrRrrr#r",
    ".........rRr#rrr",
    ".........rRrrrrr",
    ".........rr#rrrr",
    "..........rrrrr.",
  ],
  glass: [ // cracked glass heart
    ".ccc...ccc.",
    "cCCcc.ccccc",
    "cCcc#cccccc",
    "ccccc#ccccc",
    "cccc#cccccc",
    ".cccc#cccc.",
    "..ccc#ccc..",
    "...cc#cc...",
    "....c#c....",
    ".....c.....",
  ],
  moonBoots: [ // boot under a moon
    "...........yyy..",
    "............yyy.",
    "......bbbbb..yy.",
    "......bBbbb..yy.",
    "......bBbbb.yyy.",
    "......bBbbb.yy..",
    "......bbbbb.....",
    "w.....bbbbb.....",
    "ww....bbbbbb....",
    ".www..bbbbbbbbb.",
    "..wwwwbbbbbbbbbb",
    "......kkkkkkkkkk",
  ],
  spite: [ // thorned heart
    "p.ppp...ppp.p",
    ".ppppp.ppppp.",
    "ppPpppppppppp",
    ".ppppppppppp.",
    "p.ppppppppp.p",
    "...ppppppp...",
    "..p.ppppp.p..",
    ".....ppp.....",
    "......p......",
  ],
  static: [ // forked lightning
    "*........c",
    "....ccccc.",
    "...cccc...",
    "..cccc....",
    ".cccccccc.",
    "....cccc..",
    "...cccc...",
    "..ccc...*.",
    ".cc.......",
    "c.....*...",
  ],
  mega: [ // mushroom
    "....rrrrrr....",
    "..rrrwwrrrrr..",
    ".rrwwwrrrwwrr.",
    "rrrwwrrrrwwwrr",
    "rrrrrrrwwrrrrr",
    "..wwwwwwwwww..",
    "....wwwwww....",
    "....w#ww#w....",
    "....wwwwww....",
    "....wwwwww....",
  ],
  shrink: [ // four arrows closing in on a tiny star
    "nnnn........nnnn",
    "nNn..........nNn",
    "nnNn........nNnn",
    "n.nNn......nNn.n",
    "...nNn....nNn...",
    "....nnn..nnn....",
    "......y..y......",
    ".......yy.......",
    ".......yy.......",
    "......y..y......",
    "....nnn..nnn....",
    "...nNn....nNn...",
    "n.nNn......nNn.n",
    "nnNn........nNnn",
    "nNn..........nNn",
    "nnnn........nnnn",
  ],
  chaos: [ // powder barrel spraying shots
    "y.....y.....y...",
    "..y...y...y.....",
    "....y.y.y.......",
    "...mmmmmmmm.....",
    "..mkkkkkkkkm....",
    ".mMmmmmmmmmmm...",
    ".mMmmmmmmmmmm...",
    ".mMmmmmmmmmmm...",
    ".mkkkkkkkkkkm...",
    ".mMmmmmmmmmmm...",
    ".mMmmmmmmmmmm...",
    ".mkkkkkkkkkkm...",
    "..mmmmmmmmmm....",
  ],
  kinetic: [ // a round slamming into an impact burst
    "..........o.....",
    "......o..ooo..o.",
    ".......o.oyo.o..",
    "........ooyyo...",
    "...w...ooyyyyoo.",
    "wwwww.oyyY*yyyoo",
    "wwwwwwwyY**Yyyo.",
    "wwwww.oyyY*yyyoo",
    "...w...ooyyyyoo.",
    "........ooyyo...",
    ".......o.oyo.o..",
    "......o..ooo..o.",
    "..........o.....",
  ],
  payload: [ // bomb with a lit fuse
    "........y.",
    ".......y*y",
    "......m.y.",
    ".....m....",
    "..kkkk....",
    ".kkkkkk...",
    "kkKkkkkk..",
    "kKkkkkkk..",
    "kkkkkkkk..",
    "kkkkkkkk..",
    ".kkkkkk...",
    "..kkkk....",
  ],
  lazarus: [ // winged heart
    "w...........w",
    "ww.rrr.rrr.ww",
    "wwrRRrrrrrrww",
    "wwrRrrrrrrrww",
    ".wrrrrrrrrrw.",
    "..wrrrrrrrw..",
    "....rrrrr....",
    ".....rrr.....",
    "......r......",
  ],
  ringOfFire: [
    "....o..o....",
    "...oo..oo...",
    "..oyyooyyo..",
    ".oyo....oyo.",
    ".oo......oo.",
    "oo........oo",
    "oo........oo",
    ".oo......oo.",
    ".oyo....oyo.",
    "..oyyooyyo..",
    "...oooooo...",
  ],

  // ---- Armory perks without a matching upgrade ----
  potion: [
    ".....mmmm.....",
    ".....mmmm.....",
    "......ww......",
    "......ww......",
    ".....wwww.....",
    "...wwrrrrww...",
    "..wrrRrrrrrw..",
    ".wrrRrrrrrrrw.",
    ".wrRrrrrrrrrw.",
    ".wrRrrrrrrrrw.",
    ".wrrrrrrrrrrw.",
    "..wrrrrrrrrw..",
    "...wwwwwwww...",
  ],
  book: [ // tome of knowledge
    ".pppppppp.",
    "pPgggggggp",
    "pPgwwwwwgp",
    "pPgwwwwwgp",
    "pPgggggggp",
    "pPpppppppp",
    "pPpppyyppp",
    "pPppppppp.",
    "pwwwwwwww.",
  ],
  sword: [
    "..........ww",
    ".........wWw",
    "........wWw.",
    ".......wWw..",
    "......wWw...",
    ".....wWw....",
    "..g.wWw.....",
    "..ggww......",
    "...gg.......",
    "..mmgg......",
    ".mm..g......",
    "mm..........",
  ],
};

// Which icon each Armory perk uses.
const PERK_ICONS = {
  vitality: "maxHp", power: "damage", endure: "maxStamina", medic: "potion",
  satchel: "backpack", scholar: "book", arsenal: "sword",
};

// A crisp, upscaled data URL for an icon (cached).
const ICON_URLS = new Map();
function iconUrl(id, scale = 3) {
  const key = id + "@" + scale;
  if (ICON_URLS.has(key)) return ICON_URLS.get(key);
  const map = ICON_MAPS[id] || ICON_MAPS.tripleShot;
  const url = upscale(pixelSprite("icon_" + id, map, 16), scale).toDataURL();
  ICON_URLS.set(key, url);
  return url;
}
